export {default as Logo} from "./Logo.svg"
export {default as Leftarrow} from "./chevron-left.svg"
export {default as Profile} from "./profile.svg"
export {default as Heart} from "./Heart.svg"
export {default as BackBtn} from "./Icon.svg"
